'$aleph_feature'(1,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(2,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(3,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(4,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(5,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(6,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(7,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(8,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(9,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(10,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(11,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(12,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(13,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(14,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(15,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(16,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(17,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(18,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(19,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(20,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(21,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(22,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(23,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(24,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(25,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(26,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(27,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(28,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(29,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(30,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(31,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(32,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(33,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(34,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(35,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(36,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(37,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(38,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(39,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(40,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(41,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(42,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(43,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(44,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(45,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(46,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(47,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(48,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(49,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(50,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(51,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(52,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(53,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(54,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(55,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(56,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(57,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(58,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(59,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(60,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(61,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(62,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(63,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(64,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(65,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(66,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(67,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(68,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(69,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(70,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(71,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(72,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(73,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(74,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(75,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(76,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(77,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(78,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(79,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(80,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(81,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(82,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(83,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(84,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(85,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(86,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(87,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(88,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(89,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(90,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(91,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(92,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(93,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(94,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(95,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(96,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(97,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(98,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(99,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(100,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(101,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(102,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(103,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(104,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(105,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(106,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(107,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(108,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(109,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(110,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(111,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(112,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(113,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(114,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(115,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(116,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(117,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(118,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(119,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(120,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(121,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(122,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(123,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(124,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(125,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(126,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(127,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(128,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(129,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(130,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(131,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(132,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(133,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(134,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(135,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(136,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(137,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(138,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(139,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(140,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(141,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(142,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(143,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(144,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(145,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(146,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(147,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(148,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(149,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(150,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(151,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(152,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(153,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(154,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(155,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(156,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(157,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(158,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(159,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(160,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(161,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(162,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(163,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(164,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(165,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(166,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(167,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(168,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(169,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(170,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(171,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(172,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(173,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(174,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(175,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(176,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(177,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(178,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(179,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(180,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(181,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(182,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(183,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(184,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(185,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(186,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(187,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(188,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(189,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(190,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(191,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(192,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(193,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(194,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(195,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(196,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(197,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(198,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(199,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(200,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(201,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(202,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(203,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(204,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(205,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(206,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(207,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(208,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(209,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(210,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(211,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(212,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(213,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(214,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(215,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(216,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(217,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(218,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(219,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(220,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(221,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(222,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(223,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(224,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(225,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(226,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(227,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(228,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(229,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(230,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(231,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(232,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(233,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(234,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(235,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(236,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(237,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(238,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(239,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(240,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(241,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(242,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(243,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(244,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(245,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(246,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(247,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(248,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(249,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(250,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(251,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(252,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(253,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(254,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(255,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(256,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(257,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(258,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(259,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(260,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(261,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(262,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(263,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(264,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(265,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(266,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(267,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(268,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(269,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(270,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(271,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(272,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(273,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(274,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(275,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(276,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(277,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(278,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(279,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(280,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(281,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(282,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(283,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(284,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(285,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(286,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(287,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(288,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(289,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(290,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(291,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(292,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(293,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(294,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(295,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(296,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(297,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(298,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(299,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(300,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(301,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(302,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(303,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(304,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(305,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(306,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(307,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(308,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(309,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(310,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(311,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(312,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(313,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(314,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(315,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(316,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(317,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(318,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(319,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(320,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(321,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(322,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(323,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(324,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(325,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(326,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(327,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(328,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(329,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(330,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(331,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(332,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(333,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(334,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(335,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(336,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(337,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(338,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(339,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(340,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(341,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(342,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(343,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(344,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(345,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(346,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(347,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(348,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(349,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(350,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(351,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(352,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(353,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(354,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(355,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(356,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(357,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(358,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(359,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(360,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(361,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(362,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(363,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(364,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(365,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(366,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(367,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(368,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(369,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(370,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(371,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(372,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(373,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(374,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(375,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(376,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(377,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(378,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(379,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(380,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(381,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(382,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(383,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(384,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(385,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(386,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(387,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(388,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(389,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(390,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(391,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(392,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(393,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(394,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(395,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(396,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(397,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(398,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(399,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(400,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(401,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(402,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(403,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(404,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(405,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(406,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(407,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(408,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(409,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(410,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(411,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(412,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(413,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(414,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(415,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(416,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(417,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(418,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(419,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(420,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(421,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(422,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(423,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(424,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(425,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(426,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(427,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(428,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(429,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(430,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(431,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(432,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(433,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(434,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(435,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(436,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(437,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(438,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(439,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(440,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(441,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(442,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(443,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(444,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(445,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(446,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(447,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(448,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(449,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(450,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(451,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(452,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(453,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(454,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(455,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(456,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(457,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(458,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(459,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(460,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(461,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(462,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(463,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(464,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(465,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(466,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(467,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(468,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(469,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(470,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(471,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(472,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(473,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(474,[],A,pos(B),has_car(B,C)).
'$aleph_feature'(475,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(476,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(477,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(478,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(479,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(480,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(481,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(482,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(483,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(484,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(485,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(486,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(487,[],A,pos(B),(has_car(B,C),short(C))).
'$aleph_feature'(488,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(489,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(490,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(491,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(492,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(493,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(494,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(495,[],A,pos(B),(has_car(B,C),has_car(B,D),short(D))).
'$aleph_feature'(496,[],A,pos(B),(has_car(B,C),short(C),has_car(B,D))).
'$aleph_feature'(497,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature'(498,[],A,pos(B),(has_car(B,C),has_car(B,D),has_car(B,E))).
'$aleph_feature'(499,[],A,pos(B),(has_car(B,C),has_car(B,D))).
'$aleph_feature'(500,[],A,pos(B),(has_car(B,C),has_car(B,D),short(C))).
'$aleph_feature_weight'(1,1.0).
'$aleph_feature_weight'(2,1.0).
'$aleph_feature_weight'(3,1.0).
'$aleph_feature_weight'(4,1.0).
'$aleph_feature_weight'(5,1.0).
'$aleph_feature_weight'(6,1.0).
'$aleph_feature_weight'(7,1.0).
'$aleph_feature_weight'(8,1.0).
'$aleph_feature_weight'(9,1.0).
'$aleph_feature_weight'(10,1.0).
'$aleph_feature_weight'(11,1.0).
'$aleph_feature_weight'(12,1.0).
'$aleph_feature_weight'(13,1.0).
'$aleph_feature_weight'(14,1.0).
'$aleph_feature_weight'(15,1.0).
'$aleph_feature_weight'(16,1.0).
'$aleph_feature_weight'(17,1.0).
'$aleph_feature_weight'(18,1.0).
'$aleph_feature_weight'(19,1.0).
'$aleph_feature_weight'(20,1.0).
'$aleph_feature_weight'(21,1.0).
'$aleph_feature_weight'(22,1.0).
'$aleph_feature_weight'(23,1.0).
'$aleph_feature_weight'(24,1.0).
'$aleph_feature_weight'(25,1.0).
'$aleph_feature_weight'(26,1.0).
'$aleph_feature_weight'(27,1.0).
'$aleph_feature_weight'(28,1.0).
'$aleph_feature_weight'(29,1.0).
'$aleph_feature_weight'(30,1.0).
'$aleph_feature_weight'(31,1.0).
'$aleph_feature_weight'(32,1.0).
'$aleph_feature_weight'(33,1.0).
'$aleph_feature_weight'(34,1.0).
'$aleph_feature_weight'(35,1.0).
'$aleph_feature_weight'(36,1.0).
'$aleph_feature_weight'(37,1.0).
'$aleph_feature_weight'(38,1.0).
'$aleph_feature_weight'(39,1.0).
'$aleph_feature_weight'(40,1.0).
'$aleph_feature_weight'(41,1.0).
'$aleph_feature_weight'(42,1.0).
'$aleph_feature_weight'(43,1.0).
'$aleph_feature_weight'(44,1.0).
'$aleph_feature_weight'(45,1.0).
'$aleph_feature_weight'(46,1.0).
'$aleph_feature_weight'(47,1.0).
'$aleph_feature_weight'(48,1.0).
'$aleph_feature_weight'(49,1.0).
'$aleph_feature_weight'(50,1.0).
'$aleph_feature_weight'(51,1.0).
'$aleph_feature_weight'(52,1.0).
'$aleph_feature_weight'(53,1.0).
'$aleph_feature_weight'(54,1.0).
'$aleph_feature_weight'(55,1.0).
'$aleph_feature_weight'(56,1.0).
'$aleph_feature_weight'(57,1.0).
'$aleph_feature_weight'(58,1.0).
'$aleph_feature_weight'(59,1.0).
'$aleph_feature_weight'(60,1.0).
'$aleph_feature_weight'(61,1.0).
'$aleph_feature_weight'(62,1.0).
'$aleph_feature_weight'(63,1.0).
'$aleph_feature_weight'(64,1.0).
'$aleph_feature_weight'(65,1.0).
'$aleph_feature_weight'(66,1.0).
'$aleph_feature_weight'(67,1.0).
'$aleph_feature_weight'(68,1.0).
'$aleph_feature_weight'(69,1.0).
'$aleph_feature_weight'(70,1.0).
'$aleph_feature_weight'(71,1.0).
'$aleph_feature_weight'(72,1.0).
'$aleph_feature_weight'(73,1.0).
'$aleph_feature_weight'(74,1.0).
'$aleph_feature_weight'(75,1.0).
'$aleph_feature_weight'(76,1.0).
'$aleph_feature_weight'(77,1.0).
'$aleph_feature_weight'(78,1.0).
'$aleph_feature_weight'(79,1.0).
'$aleph_feature_weight'(80,1.0).
'$aleph_feature_weight'(81,1.0).
'$aleph_feature_weight'(82,1.0).
'$aleph_feature_weight'(83,1.0).
'$aleph_feature_weight'(84,1.0).
'$aleph_feature_weight'(85,1.0).
'$aleph_feature_weight'(86,1.0).
'$aleph_feature_weight'(87,1.0).
'$aleph_feature_weight'(88,1.0).
'$aleph_feature_weight'(89,1.0).
'$aleph_feature_weight'(90,1.0).
'$aleph_feature_weight'(91,1.0).
'$aleph_feature_weight'(92,1.0).
'$aleph_feature_weight'(93,1.0).
'$aleph_feature_weight'(94,1.0).
'$aleph_feature_weight'(95,1.0).
'$aleph_feature_weight'(96,1.0).
'$aleph_feature_weight'(97,1.0).
'$aleph_feature_weight'(98,1.0).
'$aleph_feature_weight'(99,1.0).
'$aleph_feature_weight'(100,1.0).
'$aleph_feature_weight'(101,1.0).
'$aleph_feature_weight'(102,1.0).
'$aleph_feature_weight'(103,1.0).
'$aleph_feature_weight'(104,1.0).
'$aleph_feature_weight'(105,1.0).
'$aleph_feature_weight'(106,1.0).
'$aleph_feature_weight'(107,1.0).
'$aleph_feature_weight'(108,1.0).
'$aleph_feature_weight'(109,1.0).
'$aleph_feature_weight'(110,1.0).
'$aleph_feature_weight'(111,1.0).
'$aleph_feature_weight'(112,1.0).
'$aleph_feature_weight'(113,1.0).
'$aleph_feature_weight'(114,1.0).
'$aleph_feature_weight'(115,1.0).
'$aleph_feature_weight'(116,1.0).
'$aleph_feature_weight'(117,1.0).
'$aleph_feature_weight'(118,1.0).
'$aleph_feature_weight'(119,1.0).
'$aleph_feature_weight'(120,1.0).
'$aleph_feature_weight'(121,1.0).
'$aleph_feature_weight'(122,1.0).
'$aleph_feature_weight'(123,1.0).
'$aleph_feature_weight'(124,1.0).
'$aleph_feature_weight'(125,1.0).
'$aleph_feature_weight'(126,1.0).
'$aleph_feature_weight'(127,1.0).
'$aleph_feature_weight'(128,1.0).
'$aleph_feature_weight'(129,1.0).
'$aleph_feature_weight'(130,1.0).
'$aleph_feature_weight'(131,1.0).
'$aleph_feature_weight'(132,1.0).
'$aleph_feature_weight'(133,1.0).
'$aleph_feature_weight'(134,1.0).
'$aleph_feature_weight'(135,1.0).
'$aleph_feature_weight'(136,1.0).
'$aleph_feature_weight'(137,1.0).
'$aleph_feature_weight'(138,1.0).
'$aleph_feature_weight'(139,1.0).
'$aleph_feature_weight'(140,1.0).
'$aleph_feature_weight'(141,1.0).
'$aleph_feature_weight'(142,1.0).
'$aleph_feature_weight'(143,1.0).
'$aleph_feature_weight'(144,1.0).
'$aleph_feature_weight'(145,1.0).
'$aleph_feature_weight'(146,1.0).
'$aleph_feature_weight'(147,1.0).
'$aleph_feature_weight'(148,1.0).
'$aleph_feature_weight'(149,1.0).
'$aleph_feature_weight'(150,1.0).
'$aleph_feature_weight'(151,1.0).
'$aleph_feature_weight'(152,1.0).
'$aleph_feature_weight'(153,1.0).
'$aleph_feature_weight'(154,1.0).
'$aleph_feature_weight'(155,1.0).
'$aleph_feature_weight'(156,1.0).
'$aleph_feature_weight'(157,1.0).
'$aleph_feature_weight'(158,1.0).
'$aleph_feature_weight'(159,1.0).
'$aleph_feature_weight'(160,1.0).
'$aleph_feature_weight'(161,1.0).
'$aleph_feature_weight'(162,1.0).
'$aleph_feature_weight'(163,1.0).
'$aleph_feature_weight'(164,1.0).
'$aleph_feature_weight'(165,1.0).
'$aleph_feature_weight'(166,1.0).
'$aleph_feature_weight'(167,1.0).
'$aleph_feature_weight'(168,1.0).
'$aleph_feature_weight'(169,1.0).
'$aleph_feature_weight'(170,1.0).
'$aleph_feature_weight'(171,1.0).
'$aleph_feature_weight'(172,1.0).
'$aleph_feature_weight'(173,1.0).
'$aleph_feature_weight'(174,1.0).
'$aleph_feature_weight'(175,1.0).
'$aleph_feature_weight'(176,1.0).
'$aleph_feature_weight'(177,1.0).
'$aleph_feature_weight'(178,1.0).
'$aleph_feature_weight'(179,1.0).
'$aleph_feature_weight'(180,1.0).
'$aleph_feature_weight'(181,1.0).
'$aleph_feature_weight'(182,1.0).
'$aleph_feature_weight'(183,1.0).
'$aleph_feature_weight'(184,1.0).
'$aleph_feature_weight'(185,1.0).
'$aleph_feature_weight'(186,1.0).
'$aleph_feature_weight'(187,1.0).
'$aleph_feature_weight'(188,1.0).
'$aleph_feature_weight'(189,1.0).
'$aleph_feature_weight'(190,1.0).
'$aleph_feature_weight'(191,1.0).
'$aleph_feature_weight'(192,1.0).
'$aleph_feature_weight'(193,1.0).
'$aleph_feature_weight'(194,1.0).
'$aleph_feature_weight'(195,1.0).
'$aleph_feature_weight'(196,1.0).
'$aleph_feature_weight'(197,1.0).
'$aleph_feature_weight'(198,1.0).
'$aleph_feature_weight'(199,1.0).
'$aleph_feature_weight'(200,1.0).
'$aleph_feature_weight'(201,1.0).
'$aleph_feature_weight'(202,1.0).
'$aleph_feature_weight'(203,1.0).
'$aleph_feature_weight'(204,1.0).
'$aleph_feature_weight'(205,1.0).
'$aleph_feature_weight'(206,1.0).
'$aleph_feature_weight'(207,1.0).
'$aleph_feature_weight'(208,1.0).
'$aleph_feature_weight'(209,1.0).
'$aleph_feature_weight'(210,1.0).
'$aleph_feature_weight'(211,1.0).
'$aleph_feature_weight'(212,1.0).
'$aleph_feature_weight'(213,1.0).
'$aleph_feature_weight'(214,1.0).
'$aleph_feature_weight'(215,1.0).
'$aleph_feature_weight'(216,1.0).
'$aleph_feature_weight'(217,1.0).
'$aleph_feature_weight'(218,1.0).
'$aleph_feature_weight'(219,1.0).
'$aleph_feature_weight'(220,1.0).
'$aleph_feature_weight'(221,1.0).
'$aleph_feature_weight'(222,1.0).
'$aleph_feature_weight'(223,1.0).
'$aleph_feature_weight'(224,1.0).
'$aleph_feature_weight'(225,1.0).
'$aleph_feature_weight'(226,1.0).
'$aleph_feature_weight'(227,1.0).
'$aleph_feature_weight'(228,1.0).
'$aleph_feature_weight'(229,1.0).
'$aleph_feature_weight'(230,1.0).
'$aleph_feature_weight'(231,1.0).
'$aleph_feature_weight'(232,1.0).
'$aleph_feature_weight'(233,1.0).
'$aleph_feature_weight'(234,1.0).
'$aleph_feature_weight'(235,1.0).
'$aleph_feature_weight'(236,1.0).
'$aleph_feature_weight'(237,1.0).
'$aleph_feature_weight'(238,1.0).
'$aleph_feature_weight'(239,1.0).
'$aleph_feature_weight'(240,1.0).
'$aleph_feature_weight'(241,1.0).
'$aleph_feature_weight'(242,1.0).
'$aleph_feature_weight'(243,1.0).
'$aleph_feature_weight'(244,1.0).
'$aleph_feature_weight'(245,1.0).
'$aleph_feature_weight'(246,1.0).
'$aleph_feature_weight'(247,1.0).
'$aleph_feature_weight'(248,1.0).
'$aleph_feature_weight'(249,1.0).
'$aleph_feature_weight'(250,1.0).
'$aleph_feature_weight'(251,1.0).
'$aleph_feature_weight'(252,1.0).
'$aleph_feature_weight'(253,1.0).
'$aleph_feature_weight'(254,1.0).
'$aleph_feature_weight'(255,1.0).
'$aleph_feature_weight'(256,1.0).
'$aleph_feature_weight'(257,1.0).
'$aleph_feature_weight'(258,1.0).
'$aleph_feature_weight'(259,1.0).
'$aleph_feature_weight'(260,1.0).
'$aleph_feature_weight'(261,1.0).
'$aleph_feature_weight'(262,1.0).
'$aleph_feature_weight'(263,1.0).
'$aleph_feature_weight'(264,1.0).
'$aleph_feature_weight'(265,1.0).
'$aleph_feature_weight'(266,1.0).
'$aleph_feature_weight'(267,1.0).
'$aleph_feature_weight'(268,1.0).
'$aleph_feature_weight'(269,1.0).
'$aleph_feature_weight'(270,1.0).
'$aleph_feature_weight'(271,1.0).
'$aleph_feature_weight'(272,1.0).
'$aleph_feature_weight'(273,1.0).
'$aleph_feature_weight'(274,1.0).
'$aleph_feature_weight'(275,1.0).
'$aleph_feature_weight'(276,1.0).
'$aleph_feature_weight'(277,1.0).
'$aleph_feature_weight'(278,1.0).
'$aleph_feature_weight'(279,1.0).
'$aleph_feature_weight'(280,1.0).
'$aleph_feature_weight'(281,1.0).
'$aleph_feature_weight'(282,1.0).
'$aleph_feature_weight'(283,1.0).
'$aleph_feature_weight'(284,1.0).
'$aleph_feature_weight'(285,1.0).
'$aleph_feature_weight'(286,1.0).
'$aleph_feature_weight'(287,1.0).
'$aleph_feature_weight'(288,1.0).
'$aleph_feature_weight'(289,1.0).
'$aleph_feature_weight'(290,1.0).
'$aleph_feature_weight'(291,1.0).
'$aleph_feature_weight'(292,1.0).
'$aleph_feature_weight'(293,1.0).
'$aleph_feature_weight'(294,1.0).
'$aleph_feature_weight'(295,1.0).
'$aleph_feature_weight'(296,1.0).
'$aleph_feature_weight'(297,1.0).
'$aleph_feature_weight'(298,1.0).
'$aleph_feature_weight'(299,1.0).
'$aleph_feature_weight'(300,1.0).
'$aleph_feature_weight'(301,1.0).
'$aleph_feature_weight'(302,1.0).
'$aleph_feature_weight'(303,1.0).
'$aleph_feature_weight'(304,1.0).
'$aleph_feature_weight'(305,1.0).
'$aleph_feature_weight'(306,1.0).
'$aleph_feature_weight'(307,1.0).
'$aleph_feature_weight'(308,1.0).
'$aleph_feature_weight'(309,1.0).
'$aleph_feature_weight'(310,1.0).
'$aleph_feature_weight'(311,1.0).
'$aleph_feature_weight'(312,1.0).
'$aleph_feature_weight'(313,1.0).
'$aleph_feature_weight'(314,1.0).
'$aleph_feature_weight'(315,1.0).
'$aleph_feature_weight'(316,1.0).
'$aleph_feature_weight'(317,1.0).
'$aleph_feature_weight'(318,1.0).
'$aleph_feature_weight'(319,1.0).
'$aleph_feature_weight'(320,1.0).
'$aleph_feature_weight'(321,1.0).
'$aleph_feature_weight'(322,1.0).
'$aleph_feature_weight'(323,1.0).
'$aleph_feature_weight'(324,1.0).
'$aleph_feature_weight'(325,1.0).
'$aleph_feature_weight'(326,1.0).
'$aleph_feature_weight'(327,1.0).
'$aleph_feature_weight'(328,1.0).
'$aleph_feature_weight'(329,1.0).
'$aleph_feature_weight'(330,1.0).
'$aleph_feature_weight'(331,1.0).
'$aleph_feature_weight'(332,1.0).
'$aleph_feature_weight'(333,1.0).
'$aleph_feature_weight'(334,1.0).
'$aleph_feature_weight'(335,1.0).
'$aleph_feature_weight'(336,1.0).
'$aleph_feature_weight'(337,1.0).
'$aleph_feature_weight'(338,1.0).
'$aleph_feature_weight'(339,1.0).
'$aleph_feature_weight'(340,1.0).
'$aleph_feature_weight'(341,1.0).
'$aleph_feature_weight'(342,1.0).
'$aleph_feature_weight'(343,1.0).
'$aleph_feature_weight'(344,1.0).
'$aleph_feature_weight'(345,1.0).
'$aleph_feature_weight'(346,1.0).
'$aleph_feature_weight'(347,1.0).
'$aleph_feature_weight'(348,1.0).
'$aleph_feature_weight'(349,1.0).
'$aleph_feature_weight'(350,1.0).
'$aleph_feature_weight'(351,1.0).
'$aleph_feature_weight'(352,1.0).
'$aleph_feature_weight'(353,1.0).
'$aleph_feature_weight'(354,1.0).
'$aleph_feature_weight'(355,1.0).
'$aleph_feature_weight'(356,1.0).
'$aleph_feature_weight'(357,1.0).
'$aleph_feature_weight'(358,1.0).
'$aleph_feature_weight'(359,1.0).
'$aleph_feature_weight'(360,1.0).
'$aleph_feature_weight'(361,1.0).
'$aleph_feature_weight'(362,1.0).
'$aleph_feature_weight'(363,1.0).
'$aleph_feature_weight'(364,1.0).
'$aleph_feature_weight'(365,1.0).
'$aleph_feature_weight'(366,1.0).
'$aleph_feature_weight'(367,1.0).
'$aleph_feature_weight'(368,1.0).
'$aleph_feature_weight'(369,1.0).
'$aleph_feature_weight'(370,1.0).
'$aleph_feature_weight'(371,1.0).
'$aleph_feature_weight'(372,1.0).
'$aleph_feature_weight'(373,1.0).
'$aleph_feature_weight'(374,1.0).
'$aleph_feature_weight'(375,1.0).
'$aleph_feature_weight'(376,1.0).
'$aleph_feature_weight'(377,1.0).
'$aleph_feature_weight'(378,1.0).
'$aleph_feature_weight'(379,1.0).
'$aleph_feature_weight'(380,1.0).
'$aleph_feature_weight'(381,1.0).
'$aleph_feature_weight'(382,1.0).
'$aleph_feature_weight'(383,1.0).
'$aleph_feature_weight'(384,1.0).
'$aleph_feature_weight'(385,1.0).
'$aleph_feature_weight'(386,1.0).
'$aleph_feature_weight'(387,1.0).
'$aleph_feature_weight'(388,1.0).
'$aleph_feature_weight'(389,1.0).
'$aleph_feature_weight'(390,1.0).
'$aleph_feature_weight'(391,1.0).
'$aleph_feature_weight'(392,1.0).
'$aleph_feature_weight'(393,1.0).
'$aleph_feature_weight'(394,1.0).
'$aleph_feature_weight'(395,1.0).
'$aleph_feature_weight'(396,1.0).
'$aleph_feature_weight'(397,1.0).
'$aleph_feature_weight'(398,1.0).
'$aleph_feature_weight'(399,1.0).
'$aleph_feature_weight'(400,1.0).
'$aleph_feature_weight'(401,1.0).
'$aleph_feature_weight'(402,1.0).
'$aleph_feature_weight'(403,1.0).
'$aleph_feature_weight'(404,1.0).
'$aleph_feature_weight'(405,1.0).
'$aleph_feature_weight'(406,1.0).
'$aleph_feature_weight'(407,1.0).
'$aleph_feature_weight'(408,1.0).
'$aleph_feature_weight'(409,1.0).
'$aleph_feature_weight'(410,1.0).
'$aleph_feature_weight'(411,1.0).
'$aleph_feature_weight'(412,1.0).
'$aleph_feature_weight'(413,1.0).
'$aleph_feature_weight'(414,1.0).
'$aleph_feature_weight'(415,1.0).
'$aleph_feature_weight'(416,1.0).
'$aleph_feature_weight'(417,1.0).
'$aleph_feature_weight'(418,1.0).
'$aleph_feature_weight'(419,1.0).
'$aleph_feature_weight'(420,1.0).
'$aleph_feature_weight'(421,1.0).
'$aleph_feature_weight'(422,1.0).
'$aleph_feature_weight'(423,1.0).
'$aleph_feature_weight'(424,1.0).
'$aleph_feature_weight'(425,1.0).
'$aleph_feature_weight'(426,1.0).
'$aleph_feature_weight'(427,1.0).
'$aleph_feature_weight'(428,1.0).
'$aleph_feature_weight'(429,1.0).
'$aleph_feature_weight'(430,1.0).
'$aleph_feature_weight'(431,1.0).
'$aleph_feature_weight'(432,1.0).
'$aleph_feature_weight'(433,1.0).
'$aleph_feature_weight'(434,1.0).
'$aleph_feature_weight'(435,1.0).
'$aleph_feature_weight'(436,1.0).
'$aleph_feature_weight'(437,1.0).
'$aleph_feature_weight'(438,1.0).
'$aleph_feature_weight'(439,1.0).
'$aleph_feature_weight'(440,1.0).
'$aleph_feature_weight'(441,1.0).
'$aleph_feature_weight'(442,1.0).
'$aleph_feature_weight'(443,1.0).
'$aleph_feature_weight'(444,1.0).
'$aleph_feature_weight'(445,1.0).
'$aleph_feature_weight'(446,1.0).
'$aleph_feature_weight'(447,1.0).
'$aleph_feature_weight'(448,1.0).
'$aleph_feature_weight'(449,1.0).
'$aleph_feature_weight'(450,1.0).
'$aleph_feature_weight'(451,1.0).
'$aleph_feature_weight'(452,1.0).
'$aleph_feature_weight'(453,1.0).
'$aleph_feature_weight'(454,1.0).
'$aleph_feature_weight'(455,1.0).
'$aleph_feature_weight'(456,1.0).
'$aleph_feature_weight'(457,1.0).
'$aleph_feature_weight'(458,1.0).
'$aleph_feature_weight'(459,1.0).
'$aleph_feature_weight'(460,1.0).
'$aleph_feature_weight'(461,1.0).
'$aleph_feature_weight'(462,1.0).
'$aleph_feature_weight'(463,1.0).
'$aleph_feature_weight'(464,1.0).
'$aleph_feature_weight'(465,1.0).
'$aleph_feature_weight'(466,1.0).
'$aleph_feature_weight'(467,1.0).
'$aleph_feature_weight'(468,1.0).
'$aleph_feature_weight'(469,1.0).
'$aleph_feature_weight'(470,1.0).
'$aleph_feature_weight'(471,1.0).
'$aleph_feature_weight'(472,1.0).
'$aleph_feature_weight'(473,1.0).
'$aleph_feature_weight'(474,1.0).
'$aleph_feature_weight'(475,1.0).
'$aleph_feature_weight'(476,1.0).
'$aleph_feature_weight'(477,1.0).
'$aleph_feature_weight'(478,1.0).
'$aleph_feature_weight'(479,1.0).
'$aleph_feature_weight'(480,1.0).
'$aleph_feature_weight'(481,1.0).
'$aleph_feature_weight'(482,1.0).
'$aleph_feature_weight'(483,1.0).
'$aleph_feature_weight'(484,1.0).
'$aleph_feature_weight'(485,1.0).
'$aleph_feature_weight'(486,1.0).
'$aleph_feature_weight'(487,1.0).
'$aleph_feature_weight'(488,1.0).
'$aleph_feature_weight'(489,1.0).
'$aleph_feature_weight'(490,1.0).
'$aleph_feature_weight'(491,1.0).
'$aleph_feature_weight'(492,1.0).
'$aleph_feature_weight'(493,1.0).
'$aleph_feature_weight'(494,1.0).
'$aleph_feature_weight'(495,1.0).
'$aleph_feature_weight'(496,1.0).
'$aleph_feature_weight'(497,1.0).
'$aleph_feature_weight'(498,1.0).
'$aleph_feature_weight'(499,1.0).
'$aleph_feature_weight'(500,1.0).
'$aleph_feature_count'(500).
